package com.aovsa.abtestingservice.models;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.Data;
import lombok.Getter;
import lombok.Setter;
import org.springframework.stereotype.Repository;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbAttribute;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbBean;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbPartitionKey;

import java.util.List;
@Setter
@DynamoDbBean
public class ExperimentModel {

    private String id;

    private String experimentName;

    private List<String> variations;

    private String author;

    @DynamoDbPartitionKey
    @DynamoDbAttribute("id")

    public String getId() {
        return id;
    }
    @DynamoDBAttribute(attributeName = "experimentName")
    public String getExperimentName() {
        return experimentName;
    }
    @DynamoDBAttribute(attributeName = "variations")
    public List<String> getVariations() {
        return variations;
    }
    @DynamoDBAttribute(attributeName = "author")
    public String getAuthor() {
        return author;
    }
}
