package com.aovsa.abtestingservice.models;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.Data;
import lombok.Setter;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbAttribute;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbBean;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbPartitionKey;

@Setter
@DynamoDbBean
public class ExperimentVariationModel {
    private String id;
    private String experimentId;
    private String variationName;
    private Double variationWeight;
    @DynamoDbPartitionKey
    @DynamoDbAttribute("id")
    public String getId() {
        return id;
    }
    @DynamoDbAttribute("experimentId")
    public String getExperimentId() {
        return experimentId;
    }
    @DynamoDbAttribute("variationName")
    public String getVariationName() {
        return variationName;
    }
    @DynamoDbAttribute("variationWeight")
    public Double getVariationWeight() {
        return variationWeight;
    }
}
